### ISSUE TITLE
Flaky action in GitHub workflow due to curl network error

### ISSUE THREAD

**Issue by weliveindetail** [open-obfuscator/o-mvll#17]
Today, I saw one of the GitHub actions fail in our staging repo due to an issue with `curl`: https://github.com/build38/o-mvll/actions/runs/5153567694
```
> Run curl -LO https://data.romainthomas.fr/omvll-deps-xcode-14.tar
  ...
  curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
  Error: Process completed with exit code 92.
```

`curl` has some kind of [retry mechanism](https://stackoverflow.com/questions/42873285/curl-retry-mechanism) that we could probably use. There may be other better solutions. I am not worried and it's not urgent. I mostly want to document this for future reference, because flaky bots can be annoying.

**Comment by romainthomas** [comment]
Ok that's weird. I think this can be solved if we move this archive to a S3/other server that is not mine.

**Comment by antoniofrighetto** [comment]
Closing this, as it should be fixed by https://github.com/open-obfuscator/o-mvll/commit/6a51a3ae0725a93a8f45d3276eed0abdeb6177c8.
