### ISSUE TITLE
The error of unable to obfuscate when using plugins on Android Studio Windows.

### ISSUE THREAD

**Issue by vietdungdev0106** [open-obfuscator/o-mvll#18]
**I have installed all the required files and libraries as instructed, but still cannot use this plugin :(**

externalNativeBuild {
            cmake {
                cppFlags '-std=c++14 -frtti -fexceptions -fpass-plugin=C:\\Users\\Administrator\\Downloads\\omvll_ndk_r25\\omvll_ndk_r25.so'
                abiFilters 'arm64-v8a'
            }
        }

**An error occurred when I started building the application.**

error: unable to load plugin 'C:\Users\Administrator\Downloads\omvll_ndk_r25\omvll_ndk_r25.so': 'Could not load library 'C:\Users\Administrator\Downloads\omvll_ndk_r25\omvll_ndk_r25.so': C:\Users\Administrator\Downloads\omvll_ndk_r25\omvll_ndk_r25.so: Can't open: Unknown error (0xC1)'
    1 error generated.

**Could you help me fix this error? I really need it.**

**Comment by romainthomas** [comment]
You are trying to use a Linux (ELF) library on Windows
