### ISSUE TITLE
O-MVLL Python Configuration problem

### ISSUE THREAD

**Issue by MinghaoLin2000** [open-obfuscator/o-mvll#2]
O-MVLL Python Configuration
[CXX1405] error when building with cmake using /home/mac/AndroidStudioProjects/butterFly/app/src/main/cpp/CMakeLists.txt: -- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/mac/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/mac/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/mac/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - broken
-- Configuring incomplete, errors occurred!
See also "/home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/CMakeError.log".

C++ build system [configure] failed while executing:
    /home/mac/Android/Sdk/cmake/3.18.1/bin/cmake \
      -H/home/mac/AndroidStudioProjects/butterFly/app/src/main/cpp \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=21 \
      -DANDROID_PLATFORM=android-21 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/home/mac/Android/Sdk/ndk/25.0.8775105 \
      -DCMAKE_ANDROID_NDK=/home/mac/Android/Sdk/ndk/25.0.8775105 \
      -DCMAKE_TOOLCHAIN_FILE=/home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/home/mac/Android/Sdk/cmake/3.18.1/bin/ninja \
      -DCMAKE_CXX_FLAGS=-fpass-plugin=/home/mac/Desktop/omvll_ndk_r25.so \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mac/AndroidStudioProjects/butterFly/app/build/intermediates/cxx/Debug/4z1w3t4m/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/mac/AndroidStudioProjects/butterFly/app/build/intermediates/cxx/Debug/4z1w3t4m/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -B/home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a \
      -GNinja
  from /home/mac/AndroidStudioProjects/butterFly/app
CMake Warning at /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android.toolchain.cmake:54 (include)
  /home/mac/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:10 (project)

CMake Warning at /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android.toolchain.cmake:54 (include)
  /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
  /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Warning at /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android.toolchain.cmake:54 (include)
  /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
  /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Warning at /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android-legacy.toolchain.cmake:415 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/mac/Android/Sdk/ndk/25.0.8775105/build/cmake/android.toolchain.cmake:54 (include)
  /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
  /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Error at /home/mac/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/home/mac/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/mac/AndroidStudioProjects/butterFly/app/.cxx/Debug/4z1w3t4m/arm64-v8a/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/home/mac/Android/Sdk/cmake/3.18.1/bin/ninja cmTC_54545 && [1/2] Building CXX object CMakeFiles/cmTC_54545.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_54545.dir/testCXXCompiler.cxx.o 
    /home/mac/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/mac/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -fpass-plugin=/home/mac/Desktop/omvll_ndk_r25.so  -fPIE -MD -MT CMakeFiles/cmTC_54545.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_54545.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_54545.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    error: ModuleNotFoundError: No module named 'omvll-config'
    ninja: build stopped: subcommand failed.

explain:
I found this issue after I input the command "source omvll.env" that the document mentioned. These are the file's contents.
export NDK_VERSION=25.0.8775105
export LD_LIBRARY_PATH=${ANDROID_HOME}/ndk/${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/lib64
export OMVLL_CONFIG=$(pwd)/app/omvll-config.py
export OMVLL_PYTHONPATH=/home/mac/Desktop/Python-3.10.7/Lib
I don't know why this issue happened?? can you help me?

Environment
Target: Android/
O-MVLL Version: OMVLL Version: 1.1.0-86087c7 / 14.0.6git (4c603efb0cca074e9238af8b4106c30add4418f6)
Compilation of O-MVLL: CI

**Comment by vietdungdev0106** [comment]
I also had the same problem as you. Have you found a solution yet?
