### ISSUE TITLE
String decoding in StackLoop doesn't work

### ISSUE THREAD

**Issue by andr-ggn** [open-obfuscator/o-mvll#35]
Hello guys, thank You for your great repo!
I m playing around string encoding and found interesting thing which I want to share with you:

You have a code for **stack loop encryption**:
```out[i] = in[i] ^ raw_key[i % sizeof(key)];```

And decryption part is:
```out[i] = in[i] ^ raw_key[i % sizeof(key)] ^ i;```

I believe that decryption part should not contain `^i` in the end

Thanks

**Comment by romainthomas** [comment]
I think you misread two lines:

https://github.com/open-obfuscator/o-mvll/blob/2a07dab881308add733d3a25ca9d16e7eb3abbb8/src/passes/strings-encoding/StringEncoding.cpp#L54-L68

https://github.com/open-obfuscator/o-mvll/blob/2a07dab881308add733d3a25ca9d16e7eb3abbb8/src/passes/strings-encoding/StringEncoding.cpp#L39-L52

So it works as expected

**Comment by antoniofrighetto** [comment]
@andr-ggn, thanks for reporting this! I fixed this via bd1440f5ce8660781113d9ebb31d5852873b6e61, if you rebase to `main` it should work as expected. This is not really the best fix, but for now it should suffice. Feel free to let us know!
