### ISSUE TITLE
How can I integrate this to Android Studio 

### ISSUE THREAD

**Issue by ramanveerji** [open-obfuscator/o-mvll#51]
How to protect my kotlin app using this in android studio? Please help me. I am new to this.

**Comment by lry127** [comment]
This tool works as a [llvm optimization pass](https://llvm.org/docs/Passes.html#introduction) to secure code. It's thus necessary for you to first translate your kotlin code to a llvm capable format in order to apply a pass on it (a popular transpiler would be [dcc](https://github.com/amimo/dcc)).

**Comment by ramanveerji** [comment]
> This tool works as a [llvm optimization pass](https://llvm.org/docs/Passes.html#introduction) to secure code. It's thus necessary for you to first translate your kotlin code to a llvm compatible format in order to apply a pass on it (a popular transpiler would be [dcc](https://github.com/amimo/dcc)).

I tried dcc but my app crashes when i use it. That's why I am looking for something to protect my app.

**Comment by lry127** [comment]
> > This tool works as a [llvm optimization pass](https://llvm.org/docs/Passes.html#introduction) to secure code. It's thus necessary for you to first translate your kotlin code to a llvm compatible format in order to apply a pass on it (a popular transpiler would be [dcc](https://github.com/amimo/dcc)).
> 
> I tried dcc but my app crashes when i use it. That's why I am looking for something to protect my app. 

private assistance is available and if commercial use is intended, contact me via email. (view it on my GitHub profile page)

**Comment by ramanveerji** [comment]
> Hello @ramanveerji ,
> 
> Thanks for contacting us. If you want to protect a Kotlin app, probably the easiest way is to use the JVM-based sister project dProtect: https://github.com/open-obfuscator/dProtect
> 
> Alternatively, if you want to take advantage of the advanced capabilities of you can certainly do what @lry127 suggests of compiling Kotlin to assembly and use o-mvll in the process. Please note that support for this scenario is out of the scope of the community-led assistance provided here.
> 
> I will meanwhile close the issue.
> 
> Best regards,
> Marc

Ok but it does not support latest 8.7 gradle i think. Is there any video about setting it up and I am very new in this.
