### ISSUE TITLE
usage of omvll.StringEncOptStack() causes application crash

### ISSUE THREAD

**Issue by akoreiko** [open-obfuscator/o-mvll#62]
Hi,
I'm trying the release version 1.1.0 from https://github.com/open-obfuscator/o-mvll/releases/download/1.1.0/omvll_ndk_r26d.tar.gz

Enabling "stack string obfuscation" via omvll.StringEncOptStack() causes application crash.
If I use omvll.StringEncOptGlobal()  instead, everything works fine.
 
Romain told me that it might be caused by the latest changes in the code.
Could you please take a look at it?

**Comment by antoniofrighetto** [comment]
Please make sure that this conforms with what you're trying to do. As from the [documentation](https://obfuscator.re/omvll/passes/strings-encoding/), when StringEncOptStack is enabled, the decoded string lives in a stack-allocated buffer. This implies that the lifetime of the buffer is tied to the lifetime of the function where the string is used. We plan to upstream an option which decodes strings on-the-fly and doesn't use neither stack-allocated buffers nor global constructors some time soon.

**Comment by antoniofrighetto** [comment]
@akoreiko You may wish to give EncOptStack a try again, 2ec6f4070f83de1b1c356fceef01ba6bbbf19082 intends to make this work correctly!
